### ISSUE TITLE
Private profiles which don't necessarily scale, but are at least easier to use 🙃 

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/profiles#307]
~~The way we currently let users install private profiles does not scale well. Chats with wego teams has raised this as a potential problem/blocker for them.~~

~~_more details coming soon..._~~

~~The task here is to:~~
~~- Investigate how we can do this better~~
~~- Write up a proposal~~

Edit: this used to be about doing scalable private profiles, but since we are not in danger of hitting major scalability issues for a while (ie: we won't have that many people trying this), we are punting that for now and focussing on making our current solution a little easier.

**Comment by nikimanoledaki** [comment]
@bigkevmcd @davidstauffer if you could please bullet the requirements and add any ideas, please :)

**Comment by bigkevmcd** [comment]
@davidstauffer and I discussed this.

We've agreed to kick the scalability problem down the line a bit...we'll add DeployKeys to the repository for enterprise customers on the basis that there won't be many of them (in the 10s).

We'll script a tool that can generate an SSH Key, associate it with a repository as a Deploy Key (via the GitHub API) and then generate a `Secret` with the base64 encoded version of the key for use by a Flux `GitRepository`.  This `Secret` can then be provided to the customer.

We'll also need to add an API endpoint to the profiles API that can grab the URL from a `GitRepository` that contains a `Profile` and return it to the client.

We'll update the client to make a call to do this, and instead of cloning the source, we fetch from the tarball and use the cloned source in the profiles directory.

**Comment by Himangini** [comment]
Simon's team has created this repo https://github.com/weaveworks/weave-gitops-enterprise-profiles [we may not have access to this] this morning

**Comment by Skarlso** [comment]
@Himangini For testing this?

**Comment by Himangini** [comment]
> @Himangini For testing this?

They wanna have a go at creating a profile for wego enterprise here

**Comment by Himangini** [comment]
Also they want to use this repository for adding the deploy keys to
> But thats the repo I think we want to be adding the deploy keys to so customers can read from it.

**Comment by aclevername** [comment]
@Himangini @Callisto13 @bigkevmcd just to clarify we did say *we* are doing user story 1 right?

**Comment by Himangini** [comment]
> @Himangini @Callisto13 @bigkevmcd just to clarify we did say _we_ are doing user story 1 right?
> 
> If thats the case can we split this issue into two sub issues? Makes it all easier to track.

@aclevername yes we are doing it. I'll turn this into an Epic and make sub tickets for each user story, sounds good?

**Comment by aclevername** [comment]
> > @Himangini @Callisto13 @bigkevmcd just to clarify we did say _we_ are doing user story 1 right?
> > If thats the case can we split this issue into two sub issues? Makes it all easier to track.
> 
> @aclevername yes we are doing it. I'll turn this into an Epic and make sub tickets for each user story, sounds good?

sounds good!

**Comment by Himangini** [comment]
Closing this, created an epic [here](https://app.zenhub.com/workspaces/pitch-black-60ed85b4f8399b0017862dbd/issues/weaveworks/profiles/314) with all the details
