### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Himangini** [weaveworks/profiles#317]
### User story 3:
As a **cx-engineer**  I can find some epic docs which tell me how to use deploy key tool

**Comment by Skarlso** [comment]
Please put every documentation into https://github.com/weaveworks/profiles-userdocs/ from now on. `userdocs` in this repository will be removed soon.

**Comment by aclevername** [comment]
@Himangini did we say we don't need this story anymore? Since we already document private profiles and nothing has changed? Idr the exact outcome of our last chat on this

**Comment by Himangini** [comment]
So the plan has changed for this and I have updated the description, we need to add docs for the usage of the deploy key tool in the [weave-gitops-enterprise-credentials](https://github.com/weaveworks/weave-gitops-enterprise-credentials) repository

**Comment by Skarlso** [comment]
This actually has been documented already in the README. Now, that the two tools have been pulled together the deployment key creation is almost a side effect. It can't be run without creating the whole entitlement. This is interesting, because what if the key needs to be rotated?

All flags which are there to configure the key's state, have been either hardcoded or documented already. Such as, the key is always read-only, it's always 2048 bits and always uses RSA for generation.
